### ISSUE TITLE
End Screens for Various Victory/Failure Endings

### ISSUE THREAD

**Issue by bbradt** [GRarer/Aurora#21]
Suggestion: add a mark in the quest system for triggering particular end states, which create the screen, and end the game.  Create end screens with display text, graphics, and restart buttons, along with whatever else is needed for a full game loop.

**Comment by bbradt** [comment]
I'll work on this

**Comment by GRarer** [comment]
`QuestStage` currently has a field `isWinState`, but this should probably be replaced with something other than a boolean since we want to support multiple endings. The actual check of whether the player has achieved a quest state should probably happen at the end of `Game.updateQuestState()`

**Comment by bbradt** [comment]
Generic structure and logic for these screens added in PR #33

**Comment by GRarer** [comment]
I've closed PR #33 because we agreed at the meeting to take a different approach.

The design I have in mind is:
- an `Ending` class with `title: string` and `description:string` (and we might add additional pieces to this later
- remove the boolean `isWinState` from `QuestStage` because we want to allow many different types of endings
- instead, give quest stages an optional field of type `Ending | undefined` that defaults to undefined, where if you reach a stage where it is defined the game ends with that ending
- check for whether the player has reached a stage with an ending inside of `Game.updateQuestState()` since we want to perform the check any time a quest is advanced
- a single UI page for endings, where the constructor takes in an `Ending` object and displays the title and description text provided by that ending object

But if anything about that sounds suboptimal to you feel free to propose a different plan.

**Comment by bbradt** [comment]
resolved in PR #43 , which was merged. This issue can likely be closed pending further changes to the EndScreens, such as injection of arbitrary components (for HTML injections, displaying stats, etc)

**Comment by bbradt** [comment]
oh also a note on PR #43 so we have a paper trail. We had to violate the access patterns in Game (Game has to call GameWindow.show) to get the ending state to update, and violate the privacy of questStage (via a getter function) to get cheats to work. The latter is already tracked in a comment in the source, but both should be made aware for any future refactoring.
