### ISSUE TITLE
Tiles in the starting set can carry state between successive runs

### ISSUE THREAD

**Issue by GRarer** [GRarer/Aurora#57]
The tiles in the starting area are defined in `WorldGenerationParameters`, which means these are actually the same wasteland tile being reused in every run. Right not wasteland, mountain, and lander don't contain any internal state that gets changed during a run, but if they did this state would carry over between runs.

**Comment by nprindle** [comment]
The easiest solution here is probably just to make `nonrandomTiles` a function that generates the tiles, instead of taking them directly, as in https://github.com/nprindle/Aurora/commit/1774c9de29ba973b3d1c1af08cf89ea8f39d6048. Then, you would have to intentionally generate tiles outside of the closure if you wanted to make any state persist, but it wouldn't happen by default anymore.
